- hosts: wordpress
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    notify: restart httpd
  - name: Create a folder
    shell: mkdir -p /root/kaizen
    notify: restart httpd
  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted 
